services:
  wikistreamkotlin:
    container_name: wikistreamkotlin
    image: wikistreamkotlin:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    restart: unless-stopped

