services:
  wikistreamkotlin:
    container_name: wikistreamkotlin
    image: wikistreamkotlin:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config:ro
    environment:
      APP_STATS_REPOSITORY_TYPE: cassandra
      SPRING_PROFILES_ACTIVE: astra
    ports:
      - "7000:7000"
    restart: unless-stopped