spring.application.name=wikistreamkotlin
spring.jackson.serialization.indent-output=true
spring.config.import=optional:file:./config/auth-secrets.properties, optional:file:./config/cassandra-secrets.properties
server.port=7000

app.stats.repository.type=${APP_STATS_REPOSITORY_TYPE:cassandra}
app.auth.enabled=${APP_AUTH_ENABLED:true}

spring.cassandra.contact-points=${CASSANDRA_CONTACT_POINTS:localhost}
spring.cassandra.port=${CASSANDRA_PORT:9042}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE_NAME:db-keyspace}
spring.cassandra.local-datacenter=${CASSANDRA_LOCAL_DATACENTER:datacenter1}
spring.cassandra.schema-action=${CASSANDRA_SCHEMA_ACTION:CREATE_IF_NOT_EXISTS}
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s

#Public values
wiki.stream.url=https://stream.wikimedia.org/v2/stream/recentchange
wiki.stream.user-agent=wiki-stream-consumer/1.0 (https://github.com/you/wiki-stream)

app.security.jwt.issuer=${APP_JWT_ISSUER:default-issuer}
app.security.jwt.secret=${APP_JWT_SECRET:default-secret}
app.security.jwt.access-token-ttl-seconds=${APP_JWT_ACCESS_TOKEN_TTL_SECONDS:42}