spring.application.name=wikistreamkotlin
spring.jackson.serialization.indent-output=true
#Public values
wiki.stream.url=https://stream.wikimedia.org/v2/stream/recentchange
wiki.stream.user-agent=wiki-stream-consumer/1.0 (https://github.com/you/wiki-stream)
